from os import path

PHONE_BASE_DMP = path.join('.', 'database', 'phone_base.dmp')
TEST_PHONE_BASE_DMP = path.join('test_phone_base.dmp')

MENU_DICT = {1: 'Показать меню',
             2: 'Открыть телефонный справочник',
             3: 'Показать все контакты',
             4: 'Найти контакт',
             5: 'Создать контакт',
             6: 'Изменить контакт',
             7: 'Удалить контакт',
             8: 'Сохранить данные на диске',
             9: 'Восстановить заводские данные',
             10: 'Выйти'}

PHONE_BOOK_BACKUP = {1: {'name': 'Иван',
                         'phone': '+79183875754',
                         'mail': 'ivan_mail@mail.ru',
                         'status': 'Друг',
                         'city': 'Краснодар'},
                     2: {'name': 'Татьяна',
                         'phone': '+79183299751',
                         'mail': 'tanya_mail@mail.ru',
                         'status': 'Семья',
                         'city': 'Краснодар'},
                     3: {'name': 'Борис>',
                         'phone': '+79185877754',
                         'mail': 'borasca_mail@mail.ru',
                         'status': 'Коллега',
                         'city': 'Краснодар'},
                     4: {'name': 'Женя',
                         'phone': '+79183233884',
                         'mail': 'evgen_mail@mail.ru',
                         'status': 'Коллега',
                         'city': 'Майкоп'},
                     5: {'name': 'Настя',
                         'phone': '+79183715454',
                         'mail': 'anastasy_mail@mail.ru',
                         'status': 'Семья',
                         'city': 'Москва'},
                     6: {'name': 'Вера',
                         'phone': '+79188972754',
                         'mail': 'vera_y_mail@mail.ru',
                         'status': 'Друг',
                         'city': 'Москва'},
                     7: {'name': 'Павел',
                         'phone': '+79183225944',
                         'mail': 'pavle18_mail@mail.ru',
                         'status': 'Коллега',
                         'city': 'Москва'},
                     8: {'name': 'Ирина',
                         'phone': '+79183292587',
                         'mail': 'irina_mail@mail.ru',
                         'status': 'Семья',
                         'city': 'Краснодар'},
                     9: {'name': 'Павел',
                         'phone': '+79185877754',
                         'mail': 'pavel_mail@mail.ru',
                         'status': 'Семья',
                         'city': 'Краснодар'},
                     10: {'name': 'Стас',
                          'phone': '+79183295566',
                          'mail': 'stas_mail@mail.ru',
                          'status': 'Коллега',
                          'city': 'Краснодар'}
                     }
